"use client";

import { motion, AnimatePresence } from "framer-motion";
import { useState } from "react";

interface ProjectBadgeProps {
  projectType: {
    category: string;
    complexity: string;
    features?: string[];
    dataSource: string;
  };
  size?: "sm" | "md" | "lg";
}

interface TooltipProps {
  content: string;
  isVisible: boolean;
  position: { x: number; y: number };
}

function Tooltip({ content, isVisible, position }: TooltipProps) {
  return (
    <AnimatePresence>
      {isVisible && (
        <motion.div
          initial={{ opacity: 0, y: 10, scale: 0.9 }}
          animate={{ opacity: 1, y: 0, scale: 1 }}
          exit={{ opacity: 0, y: 10, scale: 0.9 }}
          transition={{ duration: 0.2, ease: "easeOut" }}
          className="fixed z-50 pointer-events-none"
          style={{
            left: position.x,
            top: position.y - 40,
            transform: "translateX(-50%)",
          }}
        >
          <div className="bg-gray-900 text-white text-xs px-3 py-2 rounded-lg shadow-lg border border-gray-700 max-w-xs">
            <div className="relative">
              {content}
              {/* Arrow pointing down */}
              <div className="absolute top-full left-1/2 transform -translate-x-1/2 w-0 h-0 border-l-4 border-r-4 border-t-4 border-transparent border-t-gray-900"></div>
            </div>
          </div>
        </motion.div>
      )}
    </AnimatePresence>
  );
}

export function ProjectBadge({ projectType, size = "md" }: ProjectBadgeProps) {
  const [tooltip, setTooltip] = useState<{
    content: string;
    isVisible: boolean;
    position: { x: number; y: number };
  }>({
    content: "",
    isVisible: false,
    position: { x: 0, y: 0 },
  });

  const categoryConfig = {
    fullstack: {
      label: "Full-Stack",
      icon: "🚀",
      color: "bg-blue-100 text-blue-800 border-blue-200",
      description: "Complete web application with frontend and backend",
    },
    frontend: {
      label: "Frontend",
      icon: "⚡",
      color: "bg-purple-100 text-purple-800 border-purple-200",
      description: "Client-side application with dynamic interactions",
    },
    static: {
      label: "Static",
      icon: "🎨",
      color: "bg-green-100 text-green-800 border-green-200",
      description: "Static website with no backend dependencies",
    },
    mobile: {
      label: "Mobile",
      icon: "📱",
      color: "bg-pink-100 text-pink-800 border-pink-200",
      description: "Mobile application for iOS/Android",
    },
    backend: {
      label: "Backend",
      icon: "🔧",
      color: "bg-gray-100 text-gray-800 border-gray-200",
      description: "Server-side API and data processing",
    },
    ai: {
      label: "AI/ML",
      icon: "🤖",
      color: "bg-orange-100 text-orange-800 border-orange-200",
      description: "Artificial intelligence and machine learning",
    },
    dataviz: {
      label: "Data Viz",
      icon: "📊",
      color: "bg-cyan-100 text-cyan-800 border-cyan-200",
      description: "Data visualization and analytics dashboard",
    },
    devtool: {
      label: "Dev Tool",
      icon: "🛠️",
      color: "bg-yellow-100 text-yellow-800 border-yellow-200",
      description: "Developer productivity tool or utility",
    },
  };

  // const complexityConfig = {
  //   simple: {
  //     label: "Simple",
  //     icon: "🟢",
  //     color: "text-green-600",
  //     description: "Basic functionality with straightforward implementation",
  //   },
  //   moderate: {
  //     label: "Moderate",
  //     icon: "🟡",
  //     color: "text-yellow-600",
  //     description: "Intermediate complexity with multiple features",
  //   },
  //   complex: {
  //     label: "Complex",
  //     icon: "🟠",
  //     color: "text-orange-600",
  //     description: "Advanced features with sophisticated architecture",
  //   },
  //   enterprise: {
  //     label: "Enterprise",
  //     icon: "🔴",
  //     color: "text-red-600",
  //     description: "Large-scale application with enterprise-level features",
  //   },
  // };

  // const dataSourceConfig = {
  //   database: {
  //     label: "Dynamic Data",
  //     icon: "💾",
  //     description: "Data stored in database with real-time updates",
  //   },
  //   api: {
  //     label: "API Driven",
  //     icon: "🌐",
  //     description: "External API integration for data retrieval",
  //   },
  //   static: {
  //     label: "Static Content",
  //     icon: "📄",
  //     description: "Pre-defined content without dynamic data",
  //   },
  //   realtime: {
  //     label: "Real-time",
  //     icon: "🔄",
  //     description: "Live data streaming and real-time updates",
  //   },
  //   analytics: {
  //     label: "Analytics",
  //     icon: "📊",
  //     description: "Data-driven insights and analytics",
  //   },
  //   "ai-generated": {
  //     label: "AI Generated",
  //     icon: "🤖",
  //     description: "Content generated by artificial intelligence",
  //   },
  //   "user-generated": {
  //     label: "User Content",
  //     icon: "👥",
  //     description: "Content created by users and community",
  //   },
  //   hybrid: {
  //     label: "Hybrid",
  //     icon: "🔗",
  //     description: "Combination of multiple data sources",
  //   },
  // };

  const category =
    categoryConfig[projectType.category as keyof typeof categoryConfig];
  // const complexity =
  //   complexityConfig[projectType.complexity as keyof typeof complexityConfig];
  // const dataSource =
  //   dataSourceConfig[projectType.dataSource as keyof typeof dataSourceConfig];

  const sizeClasses = {
    sm: "text-xs px-2 py-1",
    md: "text-sm px-3 py-1.5",
    lg: "text-base px-4 py-2",
  };

  const handleMouseEnter = (event: React.MouseEvent, content: string) => {
    const rect = event.currentTarget.getBoundingClientRect();
    setTooltip({
      content,
      isVisible: true,
      position: { x: rect.left + rect.width / 2, y: rect.top },
    });
  };

  const handleMouseLeave = () => {
    setTooltip((prev) => ({ ...prev, isVisible: false }));
  };

  if (!category) return null;

  return (
    <>
      <Tooltip
        content={tooltip.content}
        isVisible={tooltip.isVisible}
        position={tooltip.position}
      />

      <div className="flex flex-wrap gap-2">
        {/* Main Category Badge */}
        <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3 }}
          className={`inline-flex items-center gap-1.5 ${sizeClasses[size]} font-medium rounded-full border ${category.color} cursor-help transition-all duration-200 hover:scale-105 hover:shadow-md`}
          onMouseEnter={(e) => handleMouseEnter(e, category.description)}
          onMouseLeave={handleMouseLeave}
        >
          <span>{category.icon}</span>
          <span>{category.label}</span>
        </motion.div>

        {/* Complexity Badge */}
        {/* <motion.div
          initial={{ opacity: 0, scale: 0.8 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.3, delay: 0.1 }}
          className={`inline-flex items-center gap-1 ${sizeClasses[size]} font-medium rounded-full bg-gray-50 text-gray-700 border border-gray-200 cursor-help transition-all duration-200 hover:scale-105 hover:shadow-md`}
          onMouseEnter={(e) => handleMouseEnter(e, complexity.description)}
          onMouseLeave={handleMouseLeave}
        >
          <span>{complexity.icon}</span>
          <span className="hidden sm:inline">{complexity.label}</span>
        </motion.div> */}

        {/* Data Source Badge */}
        {/* {dataSource && (
          <motion.div
            initial={{ opacity: 0, scale: 0.8 }}
            animate={{ opacity: 1, scale: 1 }}
            transition={{ duration: 0.3, delay: 0.2 }}
            className={`inline-flex items-center gap-1 ${sizeClasses[size]} font-medium rounded-full bg-gray-50 text-gray-700 border border-gray-200 cursor-help transition-all duration-200 hover:scale-105 hover:shadow-md`}
            onMouseEnter={(e) => handleMouseEnter(e, dataSource.description)}
            onMouseLeave={handleMouseLeave}
          >
            <span>{dataSource.icon}</span>
            <span className="hidden md:inline">{dataSource.label}</span>
          </motion.div>
        )} */}
      </div>
    </>
  );
}
